# Generated by Django 4.2.3 on 2023-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=6)),
                ('articulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productos_tabla',
            },
        ),
    ]
